apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "django-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      nodePort: {{ .Values.app.nodePort }}
  type: NodePort
